# settings.yaml - Configuración optimizada

locations:
  - remoto
  - Ecuador
  - Quito
  - España

keywords:
  # Ciencia de datos (core roles)
  - data scientist
  - data analyst
  - data engineer

  # Machine Learning e IA
  - machine learning engineer
  - AI engineer
  - inteligencia artificial

  # Variantes en español
  - científico de datos
  - analista de datos
  - ingeniero de datos

  # Otros términos útiles
  - business intelligence
  - ciencia de datos
  - big data

  # Freelance / remoto
  - remote data jobs
  - freelance data

filters:
  min_salary: 0  # Opcional: se puede usar para descartar ofertas no pagadas
  languages:
    - en
    - es
  exclude_keywords:
    - senior
    - lead
    - principal
    - architect
    - manager

# Otros parámetros opcionales
max_results_per_source: 100
date_posted_within_days: 7  # Solo ofertas recientes
